# Generated by Django 3.1.7 on 2021-04-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('device_type', models.CharField(choices=[('A', 'Actuator'), ('S', 'Sensor')], max_length=1)),
                ('data_type', models.CharField(choices=[('b', 'Bool'), ('n', 'Number'), ('s', 'String')], max_length=1)),
                ('unit', models.CharField(blank=True, default='', max_length=8)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('endpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=16)),
                ('send_time', models.DateTimeField()),
                ('recept_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='endpoint_id',
            field=models.ForeignKey(db_column='endpoint_id', on_delete=django.db.models.deletion.CASCADE, to='api.endpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name', 'endpoint_id')},
        ),
    ]
